spring.application.name=identity-service
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.uri=http://localhost:8888
spring.cloud.config.fail-fast=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

## 1. Register the circuit breaker to the health endpoint so you can monitor it
#resilience4j.circuitbreaker.instances.auditServiceBreaker.register-health-indicator=true
#
## 2. How many calls should it evaluate before deciding to trip? (The sample size)
#resilience4j.circuitbreaker.instances.auditServiceBreaker.sliding-window-type=COUNT_BASED
#resilience4j.circuitbreaker.instances.auditServiceBreaker.sliding-window-size=10
#resilience4j.circuitbreaker.instances.auditServiceBreaker.minimum-number-of-calls=5
#
## 3. What percentage of failures triggers the open state?
#resilience4j.circuitbreaker.instances.auditServiceBreaker.failure-rate-threshold=50
#
## 4. How long should it wait before trying the failing service again?
#resilience4j.circuitbreaker.instances.auditServiceBreaker.wait-duration-in-open-state=10s
#
## 5. How many test requests are allowed to check if the service is back up?
#resilience4j.circuitbreaker.instances.auditServiceBreaker.permitted-number-of-calls-in-half-open-state=3
#
## Exposes the endpoints so you can check the status at /actuator/health
#management.endpoints.web.exposure.include=health,circuitbreakers
#management.endpoint.health.show-details=always